pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:Citeck/ecos-history.git
             - git checkout develop
             - git pull
             - git push sync develop
