---
server:
  port: 8086

ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:14523/ecos_history
        username: history
        password: historypassword
      main-xa-aware:
        url: ${ecos.webapp.dataSources.main.url}
        username: ${ecos.webapp.dataSources.main.username}
        password: ${ecos.webapp.dataSources.main.password}
    x509:
      keys:
        application:
          location: classpath:ecos/x509/keys/application.key
