
server:
  port: 8086

ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:14523/ecos_history
        username: history
        password: historypassword

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: history
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

ecos-history:
  recover:
    scheduled: true
    sourceFolder: /home/impi/history_record_csv/
    errorsFolder: /home/impi/history_record_csv/errors/
  deferred-actors-job-enabled: true
